### PR TITLE
FEAT: support get gas price from ethgasstation.info

### PR DESCRIPTION
**Pull request by bitbegin**

### CODE REVIEW

**Comment by x8x** [comment]
@BeardPower Did you test differences between using gasstation and geth rpc call `eth_estimategas` https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas ?

**Comment by x8x** [comment]
MyCrypto is using `https://dev.blockscale.net/api/gasexpress.json` see https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/api/gas.ts .
Worth a look.

**Comment by bitbegin** [comment]
rpc will be good, and api of blockscale.net is not blocked in  china. these two way both ok

**Comment by bitbegin** [comment]
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas is used to estimate total gas, not for gas price

**Pull request merged**
